insert into tb_person (name, birth_date) values ('João', '1988-03-17');
insert into tb_person (name, birth_date) values ('Pedro', '2000-12-01');
insert into tb_person (name, birth_date) values ('Henrique', '1995-08-01');
insert into tb_person (name, birth_date) values ('Carla', '1999-04-01');
insert into tb_person (name, birth_date) values ('Alice', '1990-06-11');
insert into tb_person (name, birth_date) values ('Matheus', '2001-09-25');
insert into tb_person (name, birth_date) values ('Fabiana', '1989-11-03');
insert into tb_person (name, birth_date) values ('Gabriel', '2002-02-10');
insert into tb_person (name, birth_date) values ('Ana', '1999-01-13');
insert into tb_person (name, birth_date) values ('José', '1992-06-20');
insert into tb_person (name, birth_date) values ('Augusto', '1996-04-22');

insert into tb_addres (public_place, zip_code, number, city, status) values ('Street A', 100000, 1, 'city01', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street B', 110000, 2, 'city02', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street C', 120000, 3, 'city03', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street D', 130000, 4, 'city04', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street E', 140000, 5, 'city05', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street F', 150000, 6, 'city06', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street G', 160000, 7, 'city07', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street H', 170000, 8, 'city08', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street I', 180000, 9, 'city09', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street J', 190000, 10, 'city10', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street K', 191000, 11, 'city11', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street L', 181000, 12, 'city12', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street M', 171000, 13, 'city13', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street N', 161000, 14, 'city14', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street O', 151000, 15, 'city15', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street P', 141000, 16, 'city16', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street Q', 131000, 17, 'city17', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street R', 121000, 18, 'city18', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street S', 111000, 19, 'city19', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street T', 101000, 20, 'city20', 'SECONDARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street U', 102000, 21, 'city21', 'PRIMARY');
insert into tb_addres (public_place, zip_code, number, city, status) values ('Street V', 103000, 22, 'city22', 'SECONDARY');

INSERT INTO tb_person_address (person_id, address_id) VALUES (1, 3);
INSERT INTO tb_person_address (person_id, address_id) VALUES (1, 2);
INSERT INTO tb_person_address (person_id, address_id) VALUES (2, 1);
INSERT INTO tb_person_address (person_id, address_id) VALUES (2, 4);
INSERT INTO tb_person_address (person_id, address_id) VALUES (3, 5);
INSERT INTO tb_person_address (person_id, address_id) VALUES (3, 6);
INSERT INTO tb_person_address (person_id, address_id) VALUES (4, 7);
INSERT INTO tb_person_address (person_id, address_id) VALUES (4, 8);
INSERT INTO tb_person_address (person_id, address_id) VALUES (5, 9);
INSERT INTO tb_person_address (person_id, address_id) VALUES (5, 10);
INSERT INTO tb_person_address (person_id, address_id) VALUES (6, 11);
INSERT INTO tb_person_address (person_id, address_id) VALUES (6, 12);
INSERT INTO tb_person_address (person_id, address_id) VALUES (7, 13);
INSERT INTO tb_person_address (person_id, address_id) VALUES (7, 14);
INSERT INTO tb_person_address (person_id, address_id) VALUES (8, 15);
INSERT INTO tb_person_address (person_id, address_id) VALUES (8, 16);
INSERT INTO tb_person_address (person_id, address_id) VALUES (9, 17);
INSERT INTO tb_person_address (person_id, address_id) VALUES (9, 18);
INSERT INTO tb_person_address (person_id, address_id) VALUES (10, 19);
INSERT INTO tb_person_address (person_id, address_id) VALUES (10, 20);
INSERT INTO tb_person_address (person_id, address_id) VALUES (11, 21);
INSERT INTO tb_person_address (person_id, address_id) VALUES (11, 22);
